### PR TITLE
Add Django SECRET_KEY in graphite settings

### LINKED ISSUE #13: Warning at container startup
On container startup, following warning is thrown:

`/var/lib/graphite/webapp/graphite/settings.py:244: UserWarning: SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security
  warn('SECRET_KEY is set to an unsafe default. This should be set in local_settings.py for better security')`

This is due to installation of `python-django` >= 1.5, which expects SECRET_KEY to be set.

### PR DESCRIPTION
**Pull request by skstronghold**
It fixes #13

### CODE REVIEW

**Comment by SamSaffron** [comment]
nahhh .. we can not ship with a key in the file, just feed it in via env.

**Comment by skstronghold** [comment]
Which place will be ideal for this config? Docker env or supervisor

**Comment by skstronghold** [comment]
Updated config to read it from env.

**Comment by SamSaffron** [comment]
looks good :)

**Pull request merged**
